#! /bin/bash

# STEP 1 copy dicoms from conquest to lab directory
# STEP 2 check that all volumes transferred
# STEP 3 unzip dicoms
# STEP 4 convert dicoms to BIDS
# STEP 5 deface T1w anatomical image

# GET CONQUEST DIRECTORY NAMES: 
# ls /jukebox/dicom/conquest/Skyra-AWP45031/NormaL/2020
# ls /jukebox/dicom/conquest/Prisma-MSTZ400D/NormaL/2020

# RECOMMENDED TO RUN HEUDICONV IN TMUX WINDOW: 
# create a new tmux window: tmux new -s [name]
# attach to an existing window: tmux a -t [name]

# other scripts called by this one: number_of_files.py, run_heudiconv.py, deface.sh

# INPUTS: 
# $1:subjectID(001,002,010)   
# $2:session(00,01,02)   
# $3:conquest directory(just the subject directory, not the whole path)
# e.g. to run: ./step1_preproc.sh 101 00 101_0_SVD-0205-1651
# for sample project: ./step1_preproc.sh 001 01 0219191_mystudy-0219-1114

# LOAD IN GLOBAL VARIABLES
source globals.sh   

# 3 inputs:
subj=$1
session=$2
subj_dir=$3

# reminder 
read -p "Are you running in a tmux window? Press any key if you want to continue" 

# STEP 1: copy dicoms from conquest to lab directory 
echo "copying session $session dicoms"
cp -r $scanner_dir/$subj_dir $raw_dir

# STEP 2: check that all volumes transferred
echo "checking number of volumes transferred session $session"
$scripts_dir/number_of_files.py $raw_dir/$subj_dir/dcm $raw_dir/check_volumes/ $subj $session
output=${subj}_${session}_index.csv
# print output to terminal window
cat $raw_dir/check_volumes/$output

# STEP 3: unzip dicoms
# NOTE: Look at your dcm folder and check that your dicoms end in .gz. If they end in .gz, you need to run this line.
# Otherwise, don't run. If they have mutliple .gz.gz endings, you will have to run multiple times until they are no longer
# zipped!
echo "unzipping session $session dicoms"
gunzip $raw_dir/$subj_dir/dcm/*.gz # NOTE: you may have to do this multiple times if your files are double zipped

# STEP 4: convert dicoms to BIDS
echo "converting to BIDS with heudiconv"
$scripts_dir/run_heudiconv.py $subj_dir $subj $session $data_dir

# remove extra stuff generated by heudiconv
rm -rf $bids_dir/sourcedata
rm -rf $bids_dir/.heudiconv

# STEP 5: deface T1w image
echo "Running PYDEFACE on subject $subj, session $session"
$scripts_dir/deface.sh $subj $session

echo "STEP 1 PREPROC COMPLETE"
# print out number of volumes to double check good data transfer from the scanner
cat $raw_dir/check_volumes/$output

